### ISSUE TITLE
with docker 17.05.0-ce version？？

### ISSUE THREAD

**Issue by zhushaogang** [rancher/runc-cve#16]
ths!

**Comment by niusmallnan** [comment]
`17.05.0-ce` is not a stable version.
See this: https://download.docker.com/linux/static/stable/x86_64/

**Comment by vincent99** [comment]
Versions where the last digit is evenly divisibly by 3 (3/6/9/12) are "stable".  All other last digits were "edge" and were never supported by Rancher because they were only supported by Docker for a month.
