### ISSUE TITLE
Recommend patch for Docker 17.03.1-ce?

### ISSUE THREAD

**Issue by cleveng3r** [rancher/runc-cve#17]
Is the runc-v17.03.2 patch release compatible with Docker 17.03.1-ce, or will I need to upgrade to a supported version (eg. 17.06.2)?

Apologies if this is not the appropriate channel for this sort of question.

**Comment by vincent99** [comment]
We only produced builds and tested for the newest patch version of each major/minor release (`x.y.[highest]`).  Depending on what changed between .1 and .2 it may or may not work.

**Comment by cleveng3r** [comment]
Tested the patch and appears to work without issue.  Thanks!
