### ISSUE TITLE
do we have any patch for docker 1.12.1 and 17.05.0 ?

### ISSUE THREAD

**Issue by ketanp2000** [rancher/runc-cve#18]
do we have any patch for docker 1.12.1 and 17.05.0 ?

**Comment by vincent99** [comment]
No; we built and tested binaries for the highest patch version within each minor version (i.e. 1.12.6), not every possible patch version.  

And only for stable releases; after they switched to year.month.patch versioning, only months 3/6/9/12 are "stable" releases. 17.05.x was an "edge" release that was only ever supported by Docker for 1 month, 22 months ago (and never supported by Rancher).
